cam1:
    detect_path: "" # cam1_detect.py path
    weights: "" # cam1_weights.pt_path
    video_path: "" # cam_video path
    h_info_path: "" # h_info_paht; ex) ./hole_json_file/cam1_h_info.json
    conf-thres: "0.65" # confidence threshold
    epsilon: "100" # Distance from hole to wrench head threshold
    iou: "0.5" # Interaction over Union threshold
    wst: "3" # wrench head stay time

cam2:
    detect_path: ""
    weights: ""
    video_path: ""
    h_info_path: ""
    conf-thres: "0.65"
    epsilon: "100"
    iou: "0.5"
    wst: "3"
